### PR TITLE
Fix Go tests and release verification

### LINKED ISSUE #741: Workflow failure: release
## Workflow Failure

[release](https://github.com/pulumi/pulumi-tls/blob/main/.github/workflows/release.yml) has failed. See the list of failures below:

- [2025-03-15T00:47:39.000Z](https://github.com/pulumi/pulumi-tls/actions/runs/13867624941)

- [2025-03-19T12:52:44.000Z](https://github.com/pulumi/pulumi-tls/actions/runs/13867624941)

- [2025-03-19T13:03:24.000Z](https://github.com/pulumi/pulumi-tls/actions/runs/13867624941)

- [2025-03-19T13:29:35.000Z](https://github.com/pulumi/pulumi-tls/actions/runs/13867624941)

- [2025-03-19T16:21:02.000Z](https://github.com/pulumi/pulumi-tls/actions/runs/13867624941)

- [2025-03-19T16:50:44.000Z](https://github.com/pulumi/pulumi-tls/actions/runs/13867624941)

### PR DESCRIPTION
**Pull request by guineveresaenger**
The Go tests had a `replace` statement in them. This breaks the verify-release action's expectations.

The good news here is that the last three releases weren't actually broken; but now the release verification does the right thing. Also added the ability to run the Go tests locally.

A separate run of the verify release job correctly verifies the latest release and shows this fix is working: https://github.com/pulumi/pulumi-tls/actions/runs/14063534937/job/39380119347

Fixes #741.

- **Remove replace statements from go.mod**
- **Make sure test can run locally**

### CODE REVIEW

File: examples/examples_go_test.go [hunk 1]
```diff
@@ -32,10 +36,19 @@ func TestAccSelfSignedCertGoForcesNewResource(t *testing.T) {
 
 func getGoBaseOptions(t *testing.T) integration.ProgramTestOptions {
 	base := getBaseOptions()
+	goDepRoot := os.Getenv("PULUMI_GO_DEP_ROOT")
```
Comment (t0yv0) [inline examples/examples_go_test.go:39]: Curious, why is this necessary? I don't recall seeing this ever. 

This one does not have it for instance:

https://github.com/pulumi/pulumi-aws/blob/beff6ff88f215894fb4e32a1d28fe3fb4c0d1b72/examples/examples_go_test.go#L26

Comment (guineveresaenger) [reply examples/examples_go_test.go:39]: When you don't set this, running the tests locally via `go test` fails with "Could not automatically download and install resource plugin 'pulumi-resource-tls' at version v5.0.0-alpha.0+dev". 

Comparing the test output, AWS somewhere places the local binary into the test PATH; this provider does not.

Comment (t0yv0) [reply examples/examples_go_test.go:39]: Would this imply that AWS is not testing the local Go SDK build?

Comment (guineveresaenger) [reply examples/examples_go_test.go:39]: Strangely enough, AWS is testing the local build - its test output declares "warning: using pulumi-resource-aws from $PATH" on AWS.

I just can't tell where that is configured.

Comment (t0yv0) [reply examples/examples_go_test.go:39]: It's configured here: https://github.com/pulumi/pulumi-aws/blob/beff6ff88f215894fb4e32a1d28fe3fb4c0d1b72/examples/main_test.go#L28 - we need to figure out what is our preferred way to do this and lift it to ci-mgmt. 

I'm not sure why it works with PULUMI_GO_DEP_ROOT though and I don't think we should depend on it. 

https://github.com/pulumi/ci-mgmt/blob/0a6579f5c2ff2e630ba5a8b0e74ac3c1db92f981/provider-ci/internal/pkg/templates/defaults.config.yaml#L118 seems to indicate it's a legacy something going away.

Comment (guineveresaenger) [reply examples/examples_go_test.go:39]: GO_DEP_ROOT is a workaround for where providertest places the temporary program files, and then looks for Go dependencies from. AIUI, providertest already knows to use the correct dev provider 

> seems to indicate it's a legacy something going away.

I don't think that's what it implies - it says that we shouldn't use it inside CI directly (which is the case for this repository), but set it in Makefile instead, so it is in one location for all test runs (as long as you use `make test`).

I agree we should standardize, but - no other (few other?) provider has a `TestMain` function  or a `main_test.go` file, including this one. Nor do we standardize our `examples/` folders all that well to begin with - do we want to add that extra file via ci-mgmt? It seems more straightforward to use GO_DEP_ROOT via make everywhere.

I'm happy to punt on this part and force the maintainer to manually place the local binary in the $PATH if you prefer having the local test standardization question discussion elsewhere.

Comment (t0yv0) [reply examples/examples_go_test.go:39]: providertest is irrelevant as not used here.

Comment (t0yv0) [reply examples/examples_go_test.go:39]: I guess gcp sets it though I only found today it seems: https://github.com/pulumi/pulumi-gcp/blob/0876b2c88259e11263ca425d91d3c79e9efa54ae/examples/examples_go_test.go#L54

**Review by t0yv0 — APPROVED** [review]
Based on GCP precedent this seems admissible.

File: examples/examples_go_test.go (hunk 1 above)
Comment (guineveresaenger) [reply examples/examples_go_test.go:39]: Yes, sorry, I meant integration test: `"github.com/pulumi/pulumi/pkg/v3/testing/integration"`

**Comment by guineveresaenger** [comment]
Filed https://github.com/pulumi/ci-mgmt/issues/1466 to follow up here.

File: examples/examples_go_test.go (hunk 1 above)
Comment (danielrbradley) [reply examples/examples_go_test.go:39]: To help clarify the purpose of this change ... `GO_DEP_ROOT` is required by "program test" (pkg/testing/integration) when doing local SDK replacement. This is set in CI and _could_ be set in the makefile, but this means the tests are not easily runnable out of the box with standard go tooling or in an IDE.

All our repos should be striving to be as simple to set up and run as possible, so having tests which are only runnable via make is a bit of a blocker to easy onboarding. Additionally, neither CI or make is usable when wanting to attach a debugger to a test. The main thing here is that tests should configure themselves rather than require the caller to know what magic bits of environment variables need to be set.
